###################################################################

# Created by write_sdc on Mon Nov 15 21:54:31 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports VOUT]
set_load -pin_load 3.40189 [get_ports {DOUT[11]}]
set_load -pin_load 3.40189 [get_ports {DOUT[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT[0]}]
create_clock [get_ports CLK]  -name MY_CLK  -period 12.4  -waveform {0 6.2}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports RST_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports VIN]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B0[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B3[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B4[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B5[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B6[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B7[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {B8[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports VOUT]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT[0]}]
